### ISSUE TITLE
undefined local variable or method `whitespace'

### ISSUE THREAD

**Issue by lucianghinda** [joeldrapper/phlex#128]
Hello,

I am not 100% this is a bug. It might be that I am not using right phex component.

But here is a short test

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  ruby "3.1.1"

  gem "phlex"
end

class LinksComponent < Phlex::Component
  def template
    a "Home", href: "/"
    whitespace
    a "About", href: "/about"
    whitespace
    a "Contact", href: "/contact"
  end
end

m = LinksComponent.new(name: "Twitter")
m.call
```

If I run the code above, I get the following error: 

```
test-bug.rb:18:in `template': undefined local variable or method `whitespace' for #<LinksComponent:0x000000010b61f1a0 @name="Twitter", @_render_context=#<LinksComponent:0x000000010b61e9a8 @name="Twitter", @_render_context=#<LinksComponent:0x000000010b61f1a0 ...>, @_children=[#<Phlex::Tag::A:0x000000010b61ecf0 @attributes={:href=>["/"]}, @_children=[#<Phlex::Text:0x000000010b61e7f0 @content="Home">]>]>, @_children=[#<Phlex::Tag::A:0x000000010b61ecf0 @attributes={:href=>["/"]}, @_children=[#<Phlex::Text:0x000000010b61e7f0 @content="Home">]>]> (NameError)

    whitespace
    ^^^^^^^^^^
	from /.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/phlex-0.1.0/lib/phlex/component.rb:14:in `initialize'
```

I took the example from the documentation here: https://www.phlex.fun/templates/

**Comment by joeldrapper** [comment]
Hey @lucianghinda, we haven't made a release to RubyGems since the first push to reserve the name. We will be cutting a beta release soon but until then, just change your source to GitHub.

```ruby
gem "phlex", github: "joeldrapper/phlex"
```

I’ll close this issue but please re-open it if this doesn't fix the problem.

**Comment by lucianghinda** [comment]
Hi @joeldrapper 

Thank you very much for the response. I will update my Gemfile accordingly!

**Comment by joeldrapper** [comment]
No problem and sorry it doesn't mention it anywhere in the documentation. Please let me know how you find Phlex.
