### ISSUE TITLE
commonmarker dependency of phlex/markdown.rb causes app to not load on 0.5

### ISSUE THREAD

**Issue by fractaledmind** [joeldrapper/phlex#343]
The Heroku logs are:
```
heroku[web.1]: Starting process with command `bin/rails server -p ${PORT:-5000} -e production`
app[web.1]: => Booting Puma
app[web.1]: => Rails 7.0.4 application starting in production
app[web.1]: => Run `bin/rails server --help` for more startup options
app[web.1]: Exiting
app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require': cannot load such file -- commonmarker (LoadError)
app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
app[web.1]: from /app/vendor/bundle/ruby/3.1.0/bundler/gems/phlex-16edeba653fa/lib/phlex/markdown.rb:3:in `<main>'
```

Scanning the source, I see that `commonmarker` is listed as a dependency in the `docs` group in the Gemfile. This group is not downloaded in production, and thus the `require "commonmarker"` call in the `lib/phlex/markdown.rb`blows up in production.

**Comment by joeldrapper** [comment]
Ops, `Phlex::Markdown` was meant to be ignored in the Zeitwerk configuration.

**Comment by joeldrapper** [comment]
I don't know how we can test against this becuase all the Gemfile dependencies are installed in the test environment.
